# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile para crear tres máquinas: dhcp-server, c1, y c2 con IPs estáticas
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64" 

  # Configuración de la máquina servidor DHCP
  config.vm.define "server" do |server|
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.network "private_network", ip: "192.168.57.10",
    virtualbox__intnet: true
    server.vm.provision  "shell", inline: <<-SHELL
      apt-get update
      apt-get upgrade -y
      apt-get install -y isc-dhcp-server
      cp /vagrant/dhcpd.conf /etc/dhcp/
      cp /vagrant/isc-dhcp-server /etc/default/

      systemctl start isc-dhcp-server

    SHELL

  end

  config.vm.define "cliente1" do |c1|
    c1.vm.network "private_network", type: "dhcp",
    virtualbox__intnet: true
  end

  config.vm.define "cliente2" do |c2|
    c2.vm.network "private_network", type: "dhcp", mac: "0800279e0037",
    virtualbox__intnet: true
  end
end